name: Task 3 - Chuck Norris

on:
  workflow_dispatch:

jobs:
  task3:
    name: Task 3 - Chuck Norris
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        id: myRequest
        with:
          url: 'https://api.chucknorris.io/jokes/random'
          method: 'GET'

      - name: Show Response
        id: quote
        run: |
          echo "::set-output name=QUOTE::${{ fromJson(steps.myRequest.outputs.response).value }}"



      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://chuck.alexc.no/api/quote'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
                "quote": "${{ steps.quote.outputs.quote }}",
                "accessCode": "${{ secrets.ACCESS_CODE }}"
            }