name: "Quote of the day"

on: [workflow_dispatch]

jobs:
  quote:
    steps:
      - name: Fetch quote
        runs-on: ubuntu-latest
        uses: fjogeleit/http-request-action@v1
        id: getQuoteResponse
        with:
          url: "https://api.chucknorris.io/jokes/random"
          method: "GET"
      - name: Show Response
        id: quote
        run: |
          echo "::set-output name=QUOTE::${{ fromJson(steps.getQuoteResponse.outputs.response).value }}"
